### ISSUE TITLE
no language specific column in user_defined signs

### ISSUE THREAD

**Issue by 3nids** [opengisch/signalo#113]
in user defined table, drop the language specific image path for a single one (img_fr => img, value_fr => value)

**Comment by itsakifa** [comment]
@3nids at the moment signalo_app.vw_sign_symbol takes over the language specific fields from offical signs, and fills in the values from user signs in case the sign type is user defined. that's why the structure of the user signs table is the same as for official signs. Should we still change to "img" and "value" for user defined signs?

**Comment by 3nids** [comment]
this would increase the complexity of the project (handling of different columns)
